### ISSUE TITLE
libxcb support?

### ISSUE THREAD

**Issue by Ellis2781** [ghaerr/microwindows#59]
I see that this project has the nx11 library for libx11 but it would be nice to see a wrapper for libxcb. I'm sure you may have thought of this but how would you implement this?

**Comment by ghaerr** [comment]
Hello @Ellis2781,

> it would be nice to see a wrapper for libxcb

That could take a great deal of work, if you're looking for strict compatibility with existing programs using libxcb. The reason is that the nano-X wire protocol isn't the same as X11. A nano-X application could write the wire directly with not much work, that is handled mostly in nanox/nxproto.c. The majority of client requests to the server are in nanox/client.c. If the X11 libxcb application is small, and you're just looking for a way to convert those requests to nano-X protocol, that might not be too bad, unless there is complexity in the event handling/queing, etc.

We could discuss this in more depth, depending on what exactly you're looking for.

Thank you!

**Comment by lighth7015** [comment]
Hey, posted on my birthday! Cool! :D

_Ahem_, anyway- I don't think you honestly _need_ cxb support, since really there's no "protocol" to wrap. xcb's whole shtick is that it's a better xlib than xlib. Which if you wanted to do that, you can just implement an alternate API on top. :D
