### ISSUE TITLE
NanoX on Microsoft Windows

### ISSUE THREAD

**Issue by UsNizami** [ghaerr/microwindows#81]
Hi,

According to your github page nano-X can run on Windows. I have a microcontroller running ubuntu and showing GUI on screen on LCD using nano-X. Now for monitoring purpose in control room we want same screen view on our Window 10 app as well (it is getting data from micrcontroller). We just want send a dynamic data while static gui data should be in Window app.  So is there way to compile nano-X on Window 10 with Microsoft using either Microsoft Visual C++ or Cygwin. Do I have to change Makefiles significantly for that or will it work without significant rework ?

**Comment by ghaerr** [comment]
Hi @UsNizami,

> So is there way to compile nano-X on Window 10 with Microsoft using either Microsoft Visual C++ or Cygwin.

There are a couple of contributed Visual C projects for compiling Nano-X on Windows, see the `src/contrib/ports/vs2008` and `src/contrib/ports/visualstudio` directories. These originally worked, but it has been a while since these were tested. They should give you a good start in the right direction. I would think you should be able to add/subtract files from the VC project your own requirements. I don't have a Windows box with which to test, however.

Thank you!
